name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: |
          bun run build && bun run package
          bun run build:firefox && bun run package:firefox
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name || 'vTEST' }}
          files: build/*.zip
